### ISSUE TITLE
WebApp?

### ISSUE THREAD

**Issue by kordjamshidi** [IllinoisCogComp/saul#379]
I run the webapp and get the following error, did something happen during the latest changes? 
```scala
ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.ExceptionInInitializerError
  at controllers.Application.<init>(Application.scala:35)
  while locating controllers.Application
    for parameter 1 at router.Routes.<init>(Routes.scala:35)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

1 error
```

**Comment by bhargav** [comment]
Looking at this.
