### ISSUE TITLE
error when running ER example on Windows OS

### ISSUE THREAD

**Issue by drmr-anki** [IllinoisCogComp/saul#447]
I tried the sbt command "sbt "project saulExamples" "runMain edu.illinois.cs.cogcomp.saulexamples.nlp.EntityRelation.EntityRelationApp",  in cygwin terminal on Windows, but it gave the error:
![image](https://cloud.githubusercontent.com/assets/10840853/20083395/b07093b0-a521-11e6-8fff-0816f183979d.png)
It was solved with the flag"-Dfile.encoding=UTF-8 ". Maybe we should add it to the README file.

Later I had the following error, but it doesn't affect running the code. I am still able to enter the user interface and input the sentences.
![image](https://cloud.githubusercontent.com/assets/10840853/20083491/482a27f2-a522-11e6-9fa1-9144ecb236fb.png)

Not sure what to do about it.

**Comment by kordjamshidi** [comment]
This last error is not only for windows, it has been always there because of the logger. Though it does not hurt but would be great if we can find a solution that it does not appear in there.

**Comment by danyaljj** [comment]
@drmr-anki could you include the full error log? I suspect that you don't have the data necessary to run the ER example.

**Comment by drmr-anki** [comment]
Here is the full error log. Since I could run the example after adding the UTF-8 flag, I think it's related to the Windows system or the Cygwin terminal.
`java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at java.io.BufferedReader.fill(Unknown Source)
        at java.io.BufferedReader.read(Unknown Source)
        at scala.io.BufferedSource$$anonfun$iter$1$$anonfun$apply$mcI$sp$1.apply                                                                                                                                   $mcI$sp(BufferedSource.scala:38)
        at scala.io.Codec.wrap(Codec.scala:68)
        at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38                                                                                                                                   )
        at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38                                                                                                                                   )
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
        at scala.collection.Iterator$$anon$17.hasNext(Iterator.scala:511)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.io.Source.hasNext(Source.scala:226)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.io.Source.foreach(Source.scala:178)
        at scala.collection.TraversableOnce$class.addString(TraversableOnce.scal                                                                                                                                   a:320)
        at scala.io.Source.addString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala                                                                                                                                   :286)
        at scala.io.Source.mkString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala                                                                                                                                   :288)
        at scala.io.Source.mkString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala                                                                                                                                   :290)
        at scala.io.Source.mkString(Source.scala:178)
        at de.heikoseeberger.sbtheader.HeaderCreator.<init>(HeaderCreator.scala:                                                                                                                                   30)
        at de.heikoseeberger.sbtheader.HeaderCreator$.apply(HeaderCreator.scala:                                                                                                                                   65)
        at de.heikoseeberger.sbtheader.HeaderPlugin$.de$heikoseeberger$sbtheader                                                                                                                                   $HeaderPlugin$$createHeader(HeaderPlugin.scala:123)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$4$$anonfun$apply$2.                                                                                                                                   apply(HeaderPlugin.scala:114)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$4$$anonfun$apply$2.                                                                                                                                   apply(HeaderPlugin.scala:114)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(Traversable                                                                                                                                   Like.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(Traversable                                                                                                                                   Like.scala:251)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:                                                                                                                                   251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$4.apply(HeaderPlugi                                                                                                                                   n.scala:114)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$4.apply(HeaderPlugi                                                                                                                                   n.scala:114)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(Traversable                                                                                                                                   Like.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(Traversable                                                                                                                                   Like.scala:251)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:                                                                                                                                   251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at de.heikoseeberger.sbtheader.HeaderPlugin$.de$heikoseeberger$sbtheader                                                                                                                                   $HeaderPlugin$$createHeadersTask(HeaderPlugin.scala:114)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$toBeScopedSettings$                                                                                                                                   3.apply(HeaderPlugin.scala:98)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$toBeScopedSettings$                                                                                                                                   3.apply(HeaderPlugin.scala:98)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22                                                                                                                                   6)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22                                                                                                                                   6)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric                                                                                                                                   tions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (saulExamples/compile:createHeaders) java.nio.charset.UnmappableCharacte                                                                                                                                   rException: Input length = 1
[error] Total time: 4 s, completed Nov 7, 2016 9:48:42 PM
`

**Comment by bhargav** [comment]
This is fixed by the Java option "-Dfile.encoding=UTF-8 ". Updated the README.md. Closing this as fixed.
